# This patch mounts the CA key and certificate in the manager pod.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signer-ca-controller-manager
  namespace: signer-ca-system
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - name: etc-pki
              mountPath: /etc/pki
              readOnly: true
      volumes:
        - name: etc-pki
          secret:
            secretName: signer-ca
            items:
              - key: tls.key
                path: example.com/foo/ca-key.pem
              - key: tls.crt
                path: example.com/foo/ca.pem
