apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-com-foo-signer
rules:
- apiGroups:
  - certificates.k8s.io
  resourceNames:
  - example.com/foo
  resources:
  - signers
  verbs:
  - sign
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager:example-com-foo-signer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: example-com-foo-signer
subjects:
- kind: ServiceAccount
  name: default
  namespace: signer-ca-system
